stages:
  - test
  - build

services:
  - docker:dind

test:
  stage: test
  image: maven:3.6.0-jdk-8-alpine
  script:
    - mvn verify
    - chmod sonar.sh u+x && ./sonar.sh


build:
  stage: build
  image: docker:stable
  script:
    - docker build -t konkur89/simple-bank .
  only:
    - master
